### ISSUE TITLE
Creación y modificación de assets

### ISSUE THREAD

**Issue by sromerodiaz-dc** [sromerodiaz-dc/proyecto-programacion#11]
# Emplear recursos pixel art 16x16px

**Comment by cod3stealer** [comment]
De momento he logrado los siguientes assets dibujando yo mismo esto:
![ejemplo](https://github.com/cod3stealer/proyecto-programacion/assets/114175416/901753e0-9fa7-4150-ad6f-244c5baf69de)
![ejemplo2](https://github.com/cod3stealer/proyecto-programacion/assets/114175416/b7019a94-4c75-494b-9a93-ecdefd376289)
![ejemplo3](https://github.com/cod3stealer/proyecto-programacion/assets/114175416/2170ba69-cc23-4f1f-92e2-0947e04ec9d5)
![s1](https://github.com/cod3stealer/proyecto-programacion/assets/114175416/741f2672-7f35-4ed3-80ee-ff97cde63d31)
![s2](https://github.com/cod3stealer/proyecto-programacion/assets/114175416/e667ea5b-5140-4e0f-b83a-7b7ee7901330)
![w1](https://github.com/cod3stealer/proyecto-programacion/assets/114175416/c01025f3-f727-48fc-b757-a95d1339ae9c)
![w2](https://github.com/cod3stealer/proyecto-programacion/assets/114175416/c3d7d5c5-9e56-4d32-8bfe-70b9d02ee3a5)

**Comment by cod3stealer** [comment]
he modificado los assets anteriores y he creado otros en base al suelo de la ciudad de Vigo

**Comment by sromerodiaz-dc** [comment]
![busVitrasa](https://github.com/sromerodiaz-dc/proyecto-programacion/assets/114175416/1773f5ad-4628-4da2-a7bc-b45d92f96cb8)
![busVitrasa2](https://github.com/sromerodiaz-dc/proyecto-programacion/assets/114175416/18d5ecf5-c6dc-4013-9134-060d716c1e5f)
![contenedorVigo](https://github.com/sromerodiaz-dc/proyecto-programacion/assets/114175416/5f39e4ff-499a-409c-8423-69a1e80269dd)
![passvigo](https://github.com/sromerodiaz-dc/proyecto-programacion/assets/114175416/bfe66b85-4688-471a-8269-a32ac9c56f46)
![passvigoPlus](https://github.com/sromerodiaz-dc/proyecto-programacion/assets/114175416/74dea4eb-0068-449f-a30c-583469a1c244)
![portal](https://github.com/sromerodiaz-dc/proyecto-programacion/assets/114175416/3753cca5-9bab-4b67-a528-16f6ac6627a2)
![portalPared](https://github.com/sromerodiaz-dc/proyecto-programacion/assets/114175416/500c7f4f-fa8f-432e-b4bd-3cb4b134c232)

**Comment by sromerodiaz-dc** [comment]
Doy por terminado esto. Se reabrirá en un tiempo.
