### ISSUE TITLE
Implementar una base de datos

### ISSUE THREAD

**Issue by sromerodiaz-dc** [sromerodiaz-dc/proyecto-programacion#4]
# Para el empleo de logros in-game y cosas como las estadisticas es necesario el empleo de una BBDD

**Comment by cod3stealer** [comment]
Se puede hacer desde el propio IDE, arriba a la derecha en IntelliJ justo debajo del simbolo debajo de la campanita.

**Comment by cod3stealer** [comment]
Creo nueva rama de trabajo para el testeo de la base de datos ya que veo que puede servir para guardar datos del mapeo de las texturas ademas de los datos de las entidades. De todas formas, me propongo terminar otro Issue antes de ponerme con esto de pleno

**Comment by sromerodiaz-dc** [comment]
Clases nuevas creadas para la inicialización de propiedades de cada entidad a partir de una base de datos
